### ISSUE TITLE
Riak explorer gui displays 503 error if a node is added to any cluster.

### ISSUE THREAD

**Issue by ChiralMedia** [basho-labs/riak-explorer-gui#131] opened 2016-07-27 15:45 UTC
Riak explorer gui displays 503 error if a node is added to any cluster.

In this example two clusters exist (default and TestCluster) both have no nodes, Riak explorer displays both clusters in the dropdown.

Adding a node with the dcos command line results in a 503 error after the riak process has started on whichever node mesos deploys it to. The 'select cluster' drop down shows 'No result found' on being selected.

Removing the node reverts Riak explorer to a working state again.

![screenshot from 2016-07-27 16-31-33](https://cloud.githubusercontent.com/assets/8376362/17181552/781b8cfe-5418-11e6-8831-09667353e965.png)

![screenshot from 2016-07-27 16-33-17](https://cloud.githubusercontent.com/assets/8376362/17181550/77ef6dea-5418-11e6-87f0-fce195493b87.png)

![screenshot from 2016-07-27 16-32-28](https://cloud.githubusercontent.com/assets/8376362/17181551/781975b8-5418-11e6-9e5e-c103681ca0a5.png)

**Comment by paultannenbaum** [comment] 2016-07-27 17:44
@ChiralMedia Thanks for the bug report. Are you adding the node to the cluster after you have started explorer or before? If you refresh the page are you seeing the node show up in explorer, or the same behavior?

**Comment by ChiralMedia** [comment] 2016-07-28 13:59
I understand that explorer starts when the riak application (that also contains scheduler) starts under marathon. The dcos riak cluster and node commands from the cli don't work until this app has started and I need it to do so to provide the link to Riak explorer. I would assume then that explorer has already started when the cluster and nodes are added.

**Comment by paultannenbaum** [comment] 2016-07-28 17:31
Got it, that makes sense, and I just read up on the background behind the problems your seeing at https://github.com/basho-labs/riak-mesos-tools/issues/26.

I'm not sure how much of a problem this is with explorer, more likely it is incorrectly setup in the mesos-tools, but I will look into it when I have some time and get back to you with what I find out.

**Comment by sanmiguel** [comment] 2016-08-04 15:43
This was caused by using the full version of explorer, not the patched version, which was addressed at the end of basho-labs/riak-mesos-tools#26 - let's close this out!

Please feel free to reopen if you are still experiencing difficulties. Thanks!

**Closed as completed by sanmiguel** 2016-08-04 15:43 UTC
